name: CI

on:
  push:
    branches:
      - main
      - github-action
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: [ubuntu-latest, macOS-latest, windows-latest]

    strategy:
      matrix:
        platform: [android, ios]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK for Android builds
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ matrix.platform }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # Set up Kotlin Multiplatform environment
      - name: Set up Kotlin environment
        run: |
          sudo apt-get update
          sudo apt-get install -y libimobiledevice-utils ideviceinstaller ios-deploy

      # Build for Android
      - name: Build Android
        if: matrix.platform == 'android'
        run: ./gradlew assembleDebug

      # Build for iOS
      - name: Build iOS
        if: matrix.platform == 'ios'
        run: ./gradlew :shared:packForXcode

      # Run tests
      - name: Run tests
        run: ./gradlew test

  lint:
    name: Lint and Format
    runs-on: [ubuntu-latest, macOS-latest, windows-latest]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Run ktlint
      - name: Run ktlint
        run: ./gradlew ktlintCheck

  deploy:
    name: Deploy (Optional)
    needs: build
    runs-on: [ubuntu-latest, macOS-latest, windows-latest]
    steps:
      # Example for deployment: publish to GitHub Pages
      - name: Deploy artifacts
        run: echo "Add your deployment steps here."
