name: CI

on:
  push:
  pull_request:

jobs:
  build:
    name: Build and Test
    runs-on: macOS-latest

    strategy:
      matrix:
        platform: [android, ios]

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up JDK for Android builds
      - name: Set up JDK
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      # Cache Gradle
      - name: Cache Gradle
        uses: actions/cache@v3
        with:
          path: ~/.gradle/caches
          key: gradle-${{ matrix.platform }}-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}

      # Build for Android
      - name: Build Android
        if: matrix.platform == 'android'
        run: ./gradlew assembleDebug

      # Build for iOS
      - name: Build iOS
        if: matrix.platform == 'ios'
        run: ./gradlew :shared:linkDebugFrameworkIosFat

      # Run tests
      - name: Run tests
        if: matrix.platform == 'ios'
        run: ./gradlew test


  deploy:
    name: Deploy (Optional)
    needs: build
    runs-on: macOS-latest
    steps:
      # Example for deployment: publish to GitHub Pages
      - name: Deploy artifacts
        run: echo "Add your deployment steps here."
